# version: '3.1'

# Description: Default compose file, with host port for musicbrainz

services:
  db:
    build:
      context: build/postgres-prebuilt
    image: musicbrainz-docker_db:${POSTGRES_VERSION:-16}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    command: postgres -c "shared_buffers=8192MB" -c "shared_preload_libraries=pg_amqp.so"
    env_file:
      - ./default/postgres.env
    shm_size: "2GB"
    volumes:
      - /docker/musicbrainz/pgdata:/var/lib/postgresql/data
    networks:
      - npm_net
    expose:
      - "5432"

  musicbrainz:
    build:
      context: build/musicbrainz-prebuilt
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "50"
    # ports:
    #   - "${MUSICBRAINZ_WEB_SERVER_PORT}:5000"
    networks:
      - npm_net
    expose:
      - "5000"
    volumes:
      - /docker/musicbrainz/dbdump:/media/dbdump
      - /docker/musicbrainz/searchdump:/media/searchdump
    restart: unless-stopped
    env_file:
      - ./default/postgres.env
    environment:
      - MUSICBRAINZ_BASE_FTP_URL=${MUSICBRAINZ_BASE_FTP_URL:-}
      - MUSICBRAINZ_BASE_DOWNLOAD_URL=${MUSICBRAINZ_BASE_DOWNLOAD_URL:-https://data.metabrainz.org/pub/musicbrainz}
      - MUSICBRAINZ_SERVER_PROCESSES=${MUSICBRAINZ_SERVER_PROCESSES:-10}
      - MUSICBRAINZ_USE_PROXY=1
      - MUSICBRAINZ_WEB_SERVER_HOST=${MUSICBRAINZ_WEB_SERVER_HOST:-localhost}
      - MUSICBRAINZ_WEB_SERVER_PORT=${MUSICBRAINZ_WEB_SERVER_PORT:-5000}
    depends_on:
      - db
      - mq
      - search
      - redis

  indexer:
    build: build/sir
    env_file:
      - ./default/postgres.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - npm_net
    volumes:
      - ${SIR_CONFIG_PATH:-./default/indexer.ini}:/code/config.ini
    depends_on:
      - db
      - mq
      - search

  search:
    build:
      context: build/solr
      args:
        - MB_SOLR_VERSION=${MB_SOLR_VERSION:-3.4.2}
    image: musicbrainz-docker_search:${MB_SOLR_VERSION:-3.4.2}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    environment:
      - SOLR_HEAP=16g
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    networks:
      - npm_net
    expose:
      - "8983"
    volumes:
      - /docker/musicbrainz/solrdata:/opt/solr/server/solr/data
      - /docker/musicbrainz/searchdump:/media/searchdump

  mq:
    build: build/rabbitmq
    hostname: "mq"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    ulimits:
      nofile: 65536
    volumes:
      - /docker/musicbrainz/mqdata:/var/lib/rabbitmq
    networks:
      - npm_net
    expose:
      - "5672"

  redis:
    image: redis:3-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    networks:
      - npm_net
    expose:
      - "6379"

networks:
  npm_net:
    external: true